### ISSUE TITLE
encount error when i try to run my own server instance

### ISSUE THREAD

**Issue by MkLHX** [progrium/qmux#24]
Hi!
Thanks for this project! it looks awesome.

I'm trying to run my own instance on VPS using docker.
i can establish connection between client and server.
i get back a randomized url but when in try to use it i get this kind of error:
```
go_srv_1  | 2022/01/26 17:25:10 groktunnel server [grok.greenponik.com] ready!
go_srv_1  | 2022/01/26 17:25:11 75npf5e8b1.grok.greenponik.com:9999: start session
go_srv_1  | 2022/01/26 17:25:11 8m0bcmc5cm.grok.greenponik.com:9999: start session
go_srv_1  | Failed to extract vhost name: invalid method "\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xf3\xf2V\x9f;dx\xb9y]\t&\x10Q\xcbL\x97\x0f\xd9"

```

On server side:
i just change default value for port, host and addr in main.go (args aren't takes when i use them on Dockerfile script)
main.go:
```func main() {
        var port = flag.String("p", "9999", "server port to use")
        var host = flag.String("h", "grok.greenponik.com", "server hostname to use")
        var addr = flag.String("b", "54.37.11.133", "ip to bind [server only]")
        flag.Parse()
```

here my Dockerfile:
```
FROM golang:1.16-alpine

WORKDIR /app

COPY ./go.mod .
COPY ./go.sum .
RUN go mod download

COPY . /app

RUN go build

CMD ["./groktunnel"]
```
here my docker-compose.yml:
```
version: "3.8"

services:
  go_srv:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: go_srv
    network_mode: host
    restart: always
```

on client side:
main.go:
```func main() {
	var port = flag.String("p", "9999", "server port to use")
	var host = flag.String("h", "grok.greenponik.com", "server hostname to use")
	var addr = flag.String("b", "127.0.0.1", "ip to bind [server only]")
	flag.Parse()
```

Dockerfile:
```FROM golang:1.16-alpine

WORKDIR /app

COPY ./go.mod .
COPY ./go.sum .
RUN go mod download

COPY . /app

RUN go build

CMD ["./groktunnel", "8000"]
```

docker-compose.yml:
```
version: "3.8"

services:
  tunnel:
    build:
      context: .
      dockerfile: Dockerfile
    image: go_srv
    restart: always
```

How an i debug this error?
is it about the [vhost "github.com/inconshreveable/go-vhost"](https://github.com/progrium/qmux/blob/main/demos/groktunnel/main.go#L17) component?
